version: '3'
services:
  db_importer:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: ./Dockerfile  # Specify the custom Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    #uncomment to test
    # depends_on:
    #   - test_database
    command: bash -c "python load_nibrs_ucr_db.py"

  # test_database:
  #   image: postgres:16.6
  #   ports:
  #     - 5462:5432
  #   volumes:
  #     - ~/apps/postgres:/var/lib/postgresql/data
  #     - .:/app
  #   environment:
  #     - POSTGRES_PASSWORD=mysecretpassword
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=postgres
  #   working_dir: /app
